:toc:
:source-highlighter: highlightjs
:toclevels: 2
:toc-title: Table of contents

:xrefstyle: short
:section-refsig:

= Test robot

== Mainboard

=== Firmware
////
==== Version history

*v1.0.0*

. Initial implementation of 3 wheel motor and 1 thrower motor speed control.

==== Binary firmware file

link:https://github.com/ReikoR/picr21-basketball-robot-guide/raw/master/source/electronics/picr21-NUCLEO-adapter-firmware_v1_1_0.bin[picr21-NUCLEO-adapter-firmware_v1_1_0.bin]

xref:attachment$picr21-NUCLEO-adapter-firmware_v1_1_0.bin[picr21-NUCLEO-adapter-firmware_v1_1_0.bin]

Connect NUCLEO to a computer and drag or copy the *.bin file on the NOD_G431KB drive.
////
==== Sending commands to mainboard

Struct in firmware

[source,c,tabsize=2]
----
typedef struct __attribute__((packed)) Command {
  int16_t speed1;
  int16_t speed2;
  int16_t speed3;
  uint16_t throwerSpeed;
  uint16_t servo1;
  uint16_t servo2;
  uint8_t disableFailsafe;  // 1 to disable failsafe, anything else to enable
  uint16_t delimiter;
} Command;
----

Using with python's link:https://docs.python.org/3/library/struct.html[struct library]

[source,python,tabsize=4]
----
disable_failsafe = 0

struct.pack('<hhhHHHBH', speed1, speed2, speed3, thrower_speed, servo1, servo2, disable_failsafe, 0xAAAA)
----

==== Receiving data from mainboard

Struct in firmware

[source,c,tabsize=2]
----
typedef struct __attribute__((packed)) Feedback {
  int16_t speed1;
  int16_t speed2;
  int16_t speed3;
  int16_t position1;
  int16_t position2;
  int16_t position3;
  uint8_t sensors;
  uint16_t delimiter;
} Feedback;
----

Using with python's link:https://docs.python.org/3/library/struct.html[struct library]

[source,python,tabsize=4]
----
actual_speed1, actual_speed2, actual_speed3, motor1_position, motor2_position, motor3_position, sensors,  feedback_delimiter = struct.unpack('<hhhhhhBH', received_data)
----

==== Thrower speeds

Thrower speeds are sent to thrower motor controller using
https://dmrlawson.co.uk/index.php/2017/12/04/dshot-in-the-dark/[DShot protocol].
Speed values are between 48 - 2047 for 0 to 100% speed.

==== Servo values

Servo signal (PWM) frequency is 50 Hz (period 20 ms or 20000 µs).
Values correspond to pulse width in µs.
Value of 1000 changes pulse width to 1 ms (1000 µs).
Value of 2000 changes pulse width to 2 ms (2000 µs).

== Wiring

image::test_robot_electronics.svg[]

